[profile.default]
solc = "0.8.24"     # force this version (not just in pragma)
optimizer = true
optimizer_runs = 200
via_ir = true       # big win for code size on EntryPoint
src = "src"
out = "out"
libs = ["lib"]
remappings = ["account-abstraction/contracts/=lib/account-abstraction/contracts", "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"]
is-system = true
via-ir = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
